[package]
name = "FantasyOS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi="0.4.2"
log="0.4.8"
uefi-services = "0.2.0"
